name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  bot_toast: ^4.0.4
  flutter:
    sdk: flutter
  flutter_screenutil:
  provider: ^6.0.5
  regal:
    path: ../
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
