name: custom_semantics_lints
description: Custom semantics lints for ATOA internal packages.
version: 1.0.2
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.4.0
  custom_lint: ^0.2.0
  custom_lint_builder: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
