include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer:
  errors:
    constant_identifier_names: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_expression_function_bodies: true
